apiVersion: skaffold/v2beta22
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  googleCloudBuild:
    projectId: catfiadhaich-tickdev-340814
  artifacts:
    - image: us-east1-docker.pkg.dev/catfiadhaich-tickdev-340814/catfiadhaich/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
  